language: cpp

# This will run on Travis' 'new' container-based infrastructure
# https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo: false

# Safelist: focus Travis' attention on the master branch.
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: mi-toolchain
    - DOXYFILE: $TRAVIS_BUILD_DIR/mi-toolchain.doxyfile
    - GH_REPO_REF: github.ibm.com:tkornut/mi-toolchain.git
  matrix:
    - TRAVIS_4681_WORKAROUND=1

# Define matrix of test environments.
matrix:
  # Travis workarount - disable "main" test environment.
  exclude:
    - env: TRAVIS_4681_WORKAROUND=1

  include:
    # 1. Ubuntu 14.04 g++-4.9
    - env:
        - COMPILER=g++-4.9
        - OS=Ubuntu-14.04
     os: linux
     dist: trusty
     compiler: g++-4.9
      addons:
        apt:
#          sources:
#            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - g++-4.9
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      # Generate and deploy documentation - only once, for this test environment.
      after_success:
      - cd $TRAVIS_BUILD_DIR
      - chmod +x generateDocumentationAndDeploy.sh
      - ./generateDocumentationAndDeploy.sh

    # 2. Ubuntu 14.04 g++-5
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libboost-all-dev']
      env: COMPILER=g++-4.9

    # 3. Ubuntu 14.04 clang++-3.6
    - os: linux
      dist: trusty
      compiler: clang++-3.6
      env:
        - OS=Ubuntu-14.04
        - CXX=clang++-3.6
      addons:
        apt:
          packages:
            - libboost-all-dev
            - clang-3.6

    # 4. Ubuntu 14.04 clang++-3.7
    - os: linux
      dist: trusty
      compiler: clang++-3.7
      env:
        - OS=Ubuntu-14.04
        - CXX=clang++-3.7
      addons:
        apt:
          packages:
            - libboost-all-dev
            - clang-3.7
      

# Configure cmake and prepare installation dir.
before_script:
  - mkdir $TRAVIS_BUILD_DIR/../mic/
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../mic/

# Build and install.
script:
  - make install


