language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

# Define matrix to a combination of two distributions/compilers.
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode8.2
      compiler: clang

# This will run on Travis' 'new' container-based infrastructure
# https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
#sudo: false

# Safelist: focus Travis' attention on the master branch.
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: mi-toolchain
    - DOXYFILE: $TRAVIS_BUILD_DIR/mi-toolchain.doxyfile
    - GH_REPO_REF: github.ibm.com:tkornut/mi-toolchain.git

# Install dependencies
addons:
  apt:
    packages:
      - libboost-all-dev
      - libopenblas-dev
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Configure cmake and prepare installation dir.
before_script:
  - mkdir $TRAVIS_BUILD_DIR/../mic/
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../mic/

# Build and install.
script:
  - make install

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh

