language: c++

# This will run on Travis' 'new' container-based infrastructure
# https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo: false

# Safelist: focus Travis' attention on the master branch.
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: mi-toolchain
    - DOXYFILE: $TRAVIS_BUILD_DIR/mi-toolchain.doxyfile
    - GH_REPO_REF: github.ibm.com:tkornut/mi-toolchain.git
  matrix:
   # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
   - TRAVIS_4681_WORKAROUND=1


# Define matrix of test environments.
matrix:
  # Travis workaround - disable "main" test environment.
  exclude:
    - env: TRAVIS_4681_WORKAROUND=1

  include:
    # 1. Ubuntu 14.04 g++-4.8
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - g++-4.8
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      env:
        - OS=Ubuntu-14.04
        - COMPILER=g++-4.8

      # Generate and deploy documentation - only once, for this test environment.
      after_success:
      - cd $TRAVIS_BUILD_DIR
      - chmod +x generateDocumentationAndDeploy.sh
      - ./generateDocumentationAndDeploy.sh

   # 2. Ubuntu 14.04 clang-3.5
    - os: linux
      dist: trusty
      compiler: clang
      env:
        - OS=Ubuntu-14.04
        - COMPILER=clang-3.5
      addons:
        apt:
          packages:
            - libboost-all-dev
            - clang-3.5

    # 3. Ubuntu 14.04 clang-3.8
    - os: linux
      dist: trusty
      compiler: clang
      env:
        - OS=Ubuntu-14.04
        - COMPILER=clang-3.8
      addons:
        apt:
          packages:
            - libboost-all-dev
            - clang-3.8

# Configure cmake and prepare installation dir.
before_script:
  - mkdir $TRAVIS_BUILD_DIR/../mic/
  - mkdir build
  - cd build
  # Overwrite compiler!
#  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - cmake .. -DCXX=${COMPILER} -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../mic/

# Build and install.
script:
  - make CXX=${COMPILER} install VERBOSE=1

