language: cpp
os: linux
dist: trusty

# This will run on Travis' 'new' container-based infrastructure
# https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo: false

# Safelist: focus Travis' attention on the master branch.
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: mi-toolchain
    - DOXYFILE: $TRAVIS_BUILD_DIR/mi-toolchain.doxyfile
    - GH_REPO_REF: github.ibm.com:tkornut/mi-toolchain.git
  matrix:
    - TRAVIS_4681_WORKAROUND=1

# Define test matrix.
matrix:
  exclude:
    - env: TRAVIS_4681_WORKAROUND=1
  include:
    - compiler: gcc
      addons:
        apt:
#          sources:
#            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - g++-4.9
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      env:
        - CXX=g++-4.9
        - OS=Ubuntu-14.04
      # Generate and deploy documentation - only once, for this test environment.
      after_success:
      - cd $TRAVIS_BUILD_DIR
      - chmod +x generateDocumentationAndDeploy.sh
      - ./generateDocumentationAndDeploy.sh

    - compiler: gcc
      addons:
        apt:
#          sources:
#            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - g++-5
      env:
        - COMPILER=g++-5
        - OS=Ubuntu-14.04
    - compiler: clang
      addons:
        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
          packages:
            - libboost-all-dev
            - clang-3.6
      env:
        - CXX=clang++-3.6
        - OS=Ubuntu-14.04
    - compiler: clang
      addons:
        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
          packages:
            - libboost-all-dev
            - clang-3.7
      env:
        - CXX=clang++-3.7
        - OS=Ubuntu-14.04

# Configure cmake and prepare installation dir.
before_script:
  - mkdir $TRAVIS_BUILD_DIR/../mic/
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../mic/

# Build and install.
script:
  - make install


